# Generated by Django 4.1.6 on 2023-03-05 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('0032c3ed-e6f8-4c7f-ba94-b2b06f1ae8af'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('code', models.IntegerField(unique=True)),
                ('has_oscar', models.BooleanField(default=False)),
                ('cover_photo', models.ImageField(blank=True, upload_to='covers/')),
                ('year', models.PositiveSmallIntegerField()),
                ('country', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=100)),
                ('actors', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('genre', models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('horror', 'Horror'), ('romance', 'Romance'), ('sci-fi', 'Sci-Fi'), ('thriller', 'Thriller')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('93068312-fd7a-41e4-a7cf-1292dfed6f8b'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('code', models.IntegerField(unique=True)),
                ('has_oscar', models.BooleanField(default=False)),
                ('cover_photo', models.ImageField(blank=True, upload_to='covers/')),
                ('year', models.PositiveSmallIntegerField()),
                ('country', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=100)),
                ('actors', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('genre', models.CharField(blank=True, choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('horror', 'Horror'), ('romance', 'Romance'), ('sci-fi', 'Sci-Fi'), ('thriller', 'Thriller')], max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=20)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
