# Generated by Django 4.1.6 on 2023-03-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0002_alter_telegramuser_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('has_oscar', models.BooleanField(default=False)),
                ('cover_photo', models.ImageField(blank=True, upload_to='covers/')),
                ('year', models.PositiveSmallIntegerField()),
                ('country', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=100)),
                ('actors', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
    ]
