# Generated by Django 4.1.6 on 2023-03-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0003_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('code', models.IntegerField(unique=True)),
                ('has_oscar', models.BooleanField(default=False)),
                ('cover_photo', models.ImageField(blank=True, upload_to='covers/')),
                ('year', models.PositiveSmallIntegerField()),
                ('country', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=100)),
                ('actors', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='code',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
