# Generated by Django 4.1.6 on 2023-03-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0003_tguser_alter_movie_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='about',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='serial',
            name='about',
            field=models.TextField(default=''),
        ),
    ]
